[book]
authors = ["murilo ijanc"]
language = "en"
multilingual = false
src = "src"
theme = "theme"
title = "mb-platform"
description = "microbio platform"

[build]
build-dir = "book"

[output.html]
default-theme = "rust"
# additional-css = ["css/extra.css"]
copy-fonts = false
git-repository-url = "https://github.com/microbio-rs/mb-platform"
edit-url-template = "https://github.com/microbio-rs/mb-platform/edit/master/site/{path}"
site-url = "https://microbio-rs.githubio/mb-platform"
